### ISSUE TITLE
Doesn't handle KeyboardInterrupts correctly

### ISSUE THREAD

**Issue by CircuitSacul** [XuaTheGrate/Discord-Clusters#4]
Whenever I use Ctrl+C to quit the launcher, I get the following output:

```
^C[2021-01-11 17:54:46,444 Cluster#Launcher/INFO] Shutting down clusters
[2021-01-11 17:54:46,444 Cluster#Alpha/INFO] Shutting down with signal <Signals.SIGINT: 2>
Traceback (most recent call last):
  File "launcher.py", line 60, in start
Process Process-1:
    self.loop.run_forever()
  File "/opt/anaconda3/envs/dbots/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/opt/anaconda3/envs/dbots/lib/python3.7/asyncio/base_events.py", line 1750, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/anaconda3/envs/dbots/lib/python3.7/selectors.py", line 558, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "launcher.py", line 189, in <module>
    Launcher(loop).start()
  File "launcher.py", line 62, in start
Traceback (most recent call last):
  File "/opt/anaconda3/envs/dbots/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/dbots/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ld/programming/DiscordBots/Discord-Clusters/bot.py", line 33, in __init__
    self.run(kwargs['token'])
  File "/opt/anaconda3/envs/dbots/lib/python3.7/site-packages/discord/client.py", line 714, in run
    _cleanup_loop(loop)
  File "/opt/anaconda3/envs/dbots/lib/python3.7/site-packages/discord/client.py", line 90, in _cleanup_loop
    _cancel_tasks(loop)
  File "/opt/anaconda3/envs/dbots/lib/python3.7/site-packages/discord/client.py", line 75, in _cancel_tasks
    loop.run_until_complete(asyncio.gather(*tasks, return_exceptions=True))
  File "/opt/anaconda3/envs/dbots/lib/python3.7/asyncio/base_events.py", line 585, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
    self.loop.run_until_complete(self.shutdown())
  File "/opt/anaconda3/envs/dbots/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "launcher.py", line 97, in shutdown
    self.cleanup()
  File "launcher.py", line 70, in cleanup
    self.loop.close()
  File "/opt/anaconda3/envs/dbots/lib/python3.7/asyncio/unix_events.py", line 55, in close
    super().close()
  File "/opt/anaconda3/envs/dbots/lib/python3.7/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
Task was destroyed but it is pending!
task: <Task pending coro=<Launcher.rebooter() running at launcher.py:119> wait_for=<Future cancelled> cb=[Launcher.task_complete()]>
```

I've tried many different things but I can't seem to fix this. Do you have any solutions?

**Comment by CircuitSacul** [comment]
I found the problem, it's fixed here https://github.com/XuaTheGrate/Discord-Clusters/pull/5
